SET local check_function_bodies = off;

CREATE EXTENSION "pg_cron";

CREATE EXTENSION "pg_net" SCHEMA "extensions";

CREATE TABLE "public"."favorite_teams" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "teams"      jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "favorite_teams_pkey" PRIMARY KEY (id),
  CONSTRAINT "favorite_teams_user_id_key" UNIQUE (user_id)
);

ALTER TABLE "public"."favorite_teams"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."hate_teams" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "teams"      jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "hate_teams_pkey" PRIMARY KEY (id),
  CONSTRAINT "hate_teams_user_id_key" UNIQUE (user_id)
);

ALTER TABLE "public"."hate_teams"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."league_teams" (
  "league_id"         bigint                   NOT NULL,
  "team_id"           bigint                   NOT NULL,
  "season_id"         bigint                   NOT NULL,
  "season_start_date" date,
  "season_end_date"   date,
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "league_teams_pkey" PRIMARY KEY (league_id, team_id, season_id)
);

ALTER TABLE "public"."league_teams"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."leagues" (
  "id"                     bigint                   NOT NULL,
  "code"                   text                     NOT NULL,
  "name"                   text                     NOT NULL,
  "logo"                   text,
  "type"                   text,
  "country"                text,
  "country_code"           text,
  "current_season_id"      bigint,
  "season_start_date"      date,
  "season_end_date"        date,
  "current_matchday"       integer,
  "is_visible"             boolean                  NOT NULL DEFAULT true,
  "display_order"          integer                  NOT NULL DEFAULT 0,
  "updated_at"             timestamp with time zone NOT NULL DEFAULT now(),
  "teams_synced_season_id" bigint,
  "teams_synced_at"        timestamp with time zone,
  CONSTRAINT "leagues_code_key" UNIQUE (code),
  CONSTRAINT "leagues_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."leagues"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."match_alerts" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "match_id"        integer                  NOT NULL,
  "reminder_time"   integer                  NOT NULL,
  "home_team"       text                     NOT NULL,
  "away_team"       text                     NOT NULL,
  "home_team_icon"  text                     NOT NULL,
  "away_team_icon"  text                     NOT NULL,
  "match_start"     timestamp with time zone NOT NULL,
  "match_time_text" text,
  "sent"            boolean                  NOT NULL DEFAULT false,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "origin"          text                     DEFAULT 'manual'::text,
  "send_at"         timestamp with time zone,
  "status"          text                     NOT NULL DEFAULT 'pending'::text,
  "sent_at"         timestamp with time zone,
  "attempt_count"   integer                  NOT NULL DEFAULT 0,
  "last_error"      text,
  "home_team_id"    bigint,
  "away_team_id"    bigint,
  CONSTRAINT "match_alerts_pkey" PRIMARY KEY (id),
  CONSTRAINT "match_alerts_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text]))),
  "user_id"         uuid                     NOT NULL DEFAULT auth.uid(),
  CONSTRAINT "match_alerts_user_id_match_id_key" UNIQUE (user_id, match_id)
);

ALTER TABLE "public"."match_alerts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."subscribed_leagues" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "leagues"    jsonb                    NOT NULL DEFAULT '[]'::jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "subscribed_leagues_pkey" PRIMARY KEY (id),
  CONSTRAINT "subscribed_leagues_user_id_key" UNIQUE (user_id)
);

ALTER TABLE "public"."subscribed_leagues"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."teams" (
  "id"           bigint                   NOT NULL,
  "name"         text                     NOT NULL,
  "short_name"   text,
  "tla"          text,
  "icon"         text,
  "country"      text,
  "country_code" text,
  "is_visible"   boolean                  NOT NULL DEFAULT true,
  "updated_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "teams_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."teams"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_devices" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"         uuid                     NOT NULL,
  "expo_push_token" text                     NOT NULL,
  "created_at"      timestamp with time zone DEFAULT now(),
  "updated_at"      timestamp with time zone DEFAULT now(),
  CONSTRAINT "user_devices_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."user_preferences" (
  "enable_reminders" boolean                  NOT NULL DEFAULT true,
  "reminder_time"    integer                  NOT NULL DEFAULT 30,
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"          uuid                     NOT NULL DEFAULT auth.uid(),
  CONSTRAINT "user_preferences_pkey" PRIMARY KEY (user_id),
  CONSTRAINT "user_preferences_user_id_unique" UNIQUE (user_id)
);

ALTER TABLE "public"."user_preferences"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.apply_league_team_sync (
  p_league_id         bigint,
  p_season_id         bigint,
  p_season_start_date date,
  p_season_end_date   date,
  p_teams             jsonb
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
begin
  -- Prevent an empty API response from deleting memberships.
  if p_teams is null
     or jsonb_typeof(p_teams) <> 'array'
     or jsonb_array_length(p_teams) = 0 then
    raise exception 'The team list cannot be empty';
  end if;

  -- Make sure this is still the league's current season.
  if not exists (
    select 1
    from public.leagues
    where id = p_league_id
      and current_season_id = p_season_id
  ) then
    raise exception 'The provided season is not the league current season';
  end if;

  -- Insert new teams and update existing teams.
  insert into public.teams (
    id,
    name,
    short_name,
    tla,
    icon,
    country,
    country_code,
    updated_at
  )
  select
    team.id,
    team.name,
    team.short_name,
    team.tla,
    team.icon,
    team.country,
    team.country_code,
    now()
  from jsonb_to_recordset(p_teams) as team (
    id bigint,
    name text,
    short_name text,
    tla text,
    icon text,
    country text,
    country_code text
  )
  on conflict (id)
  do update set
    name = excluded.name,
    short_name = excluded.short_name,
    tla = excluded.tla,
    icon = excluded.icon,
    country = excluded.country,
    country_code = excluded.country_code,
    updated_at = now();

  -- Clear this league's existing membership for this season.
  delete from public.league_teams
  where league_id = p_league_id
    and season_id = p_season_id;

  -- Insert the current membership.
  insert into public.league_teams (
    league_id,
    team_id,
    season_id,
    season_start_date,
    season_end_date,
    updated_at
  )
  select
    p_league_id,
    team.id,
    p_season_id,
    p_season_start_date,
    p_season_end_date,
    now()
  from jsonb_to_recordset(p_teams) as team (
    id bigint
  );

  -- Record that this league has been synchronized.
  update public.leagues
  set
    teams_synced_season_id = p_season_id,
    teams_synced_at = now()
  where id = p_league_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.auto_set_user_id()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
    NEW.user_id = auth.uid();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.claim_due_match_alerts (
  batch_size integer DEFAULT 100
)
  RETURNS SETOF public.match_alerts
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  with due_alerts as (
    select alert.id
    from public.match_alerts as alert
    where alert.status = 'pending'
      and alert.send_at <= now()
      and alert.match_start > now()
      and alert.attempt_count < 3
    order by alert.send_at
    for update skip locked
    limit greatest(1, least(batch_size, 100))
  ),
  claimed_alerts as (
    update public.match_alerts as alert
    set
      status = 'processing',
      attempt_count = alert.attempt_count + 1,
      last_error = null,
      updated_at = now()
    from due_alerts
    where alert.id = due_alerts.id
    returning alert.*
  )
  select *
  from claimed_alerts;
$function$;

CREATE OR REPLACE FUNCTION public.get_current_teams_for_leagues (
  selected_league_codes text[]
)
  RETURNS TABLE (
    id         bigint,
    name       text,
    short_name text,
    icon       text
  )
  LANGUAGE sql
  STABLE
  SET search_path TO ''
  AS $function$
  select distinct
    t.id,
    t.name,
    t.short_name,
    t.icon
  from public.teams t
  join public.league_teams lt
    on lt.team_id = t.id
  join public.leagues l
    on l.id = lt.league_id
  where l.code = any(selected_league_codes)
    and lt.season_id = l.current_season_id
    and l.is_visible = true
    and t.is_visible = true
  order by t.name;
$function$;

CREATE OR REPLACE FUNCTION public.prepare_match_alert()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO ''
  AS $function$
begin
  -- Calculate the exact notification time.
  new.send_at :=
    new.match_start -
    (new.reminder_time * interval '1 minute');

  -- If an existing alert's time changes, prepare it to be sent again.
  if tg_op = 'UPDATE'
    and (
      new.match_start is distinct from old.match_start
      or new.reminder_time is distinct from old.reminder_time
    )
  then
    new.sent := false;
    new.status := 'pending';
    new.sent_at := null;
    new.attempt_count := 0;
    new.last_error := null;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.update_timestamp()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

ALTER TABLE "public"."favorite_teams"
  ADD CONSTRAINT "favorite_teams_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."hate_teams"
  ADD CONSTRAINT "hate_teams_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."league_teams"
  ADD CONSTRAINT "league_teams_league_id_fkey" FOREIGN KEY (league_id) REFERENCES public.leagues(id) ON DELETE CASCADE;

ALTER TABLE "public"."subscribed_leagues"
  ADD CONSTRAINT "subscribed_leagues_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."league_teams"
  ADD CONSTRAINT "league_teams_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_devices"
  ADD CONSTRAINT "user_devices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_favorite_teams_user_id ON public.favorite_teams USING btree (user_id);

CREATE INDEX idx_hate_teams_user_id ON public.hate_teams USING btree (user_id);

CREATE INDEX idx_subscribed_leagues_user_id ON public.subscribed_leagues USING btree (user_id);

CREATE INDEX league_teams_league_season_idx ON public.league_teams USING btree (league_id, season_id);

CREATE INDEX league_teams_team_idx ON public.league_teams USING btree (team_id);

CREATE INDEX match_alerts_pending_send_at_idx ON public.match_alerts USING btree (send_at)
  WHERE (status = 'pending'::text);

CREATE INDEX teams_name_idx ON public.teams USING btree (name);

CREATE UNIQUE INDEX user_devices_expo_push_token_idx ON public.user_devices USING btree (expo_push_token);

CREATE TRIGGER set_user_id_on_favorite_teams_insert
  BEFORE INSERT ON public.favorite_teams
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_set_user_id();

CREATE TRIGGER update_favorite_teams_updated_at
  BEFORE UPDATE ON public.favorite_teams
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER set_user_id_on_hate_teams_insert
  BEFORE INSERT ON public.hate_teams
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_set_user_id();

CREATE TRIGGER update_hate_teams_updated_at
  BEFORE UPDATE ON public.hate_teams
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER prepare_match_alert_trigger
  BEFORE INSERT OR UPDATE OF match_start, reminder_time ON public.match_alerts
  FOR EACH ROW
  EXECUTE FUNCTION public.prepare_match_alert();

CREATE TRIGGER set_timestamp
  BEFORE UPDATE ON public.match_alerts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_timestamp();

CREATE TRIGGER set_user_id_on_insert
  BEFORE INSERT ON public.subscribed_leagues
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_set_user_id();

CREATE TRIGGER update_subscribed_leagues_updated_at
  BEFORE UPDATE ON public.subscribed_leagues
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_user_preferences_timestamp
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW
  EXECUTE FUNCTION public.update_timestamp();

CREATE POLICY "Users can delete own favorite teams" ON "public"."favorite_teams"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert own favorite teams" ON "public"."favorite_teams"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update own favorite teams" ON "public"."favorite_teams"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view own favorite teams" ON "public"."favorite_teams"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can delete own hate teams" ON "public"."hate_teams"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert own hate teams" ON "public"."hate_teams"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update own hate teams" ON "public"."hate_teams"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view own hate teams" ON "public"."hate_teams"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Authenticated users can read team memberships" ON "public"."league_teams"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."leagues"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Users can delete own subscribed leagues" ON "public"."subscribed_leagues"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert own subscribed leagues" ON "public"."subscribed_leagues"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update own subscribed leagues" ON "public"."subscribed_leagues"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view own subscribed leagues" ON "public"."subscribed_leagues"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Authenticated users can read visible teams" ON "public"."teams"
  FOR SELECT
  TO "authenticated"
  USING ((is_visible = true));

CREATE POLICY "Enable read access for all authenticated users" ON "public"."teams"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Prevent delete" ON "public"."user_preferences"
  FOR DELETE
  TO PUBLIC
  USING (false);

COMMENT ON EXTENSION "pg_cron" IS 'Job scheduler for PostgreSQL';

COMMENT ON EXTENSION "pg_net" IS 'Async HTTP';

REVOKE ALL ON FUNCTION "public"."apply_league_team_sync"(bigint, bigint, date, date, jsonb) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."apply_league_team_sync"(bigint, bigint, date, date, jsonb) TO "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."auto_set_user_id"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."claim_due_match_alerts"(integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."claim_due_match_alerts"(integer) TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_current_teams_for_leagues"(text[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_current_teams_for_leagues"(text[]) TO "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."prepare_match_alert"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."update_timestamp"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."update_updated_at_column"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."favorite_teams" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."hate_teams" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."league_teams" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."leagues" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."match_alerts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subscribed_leagues" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."teams" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_devices" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_preferences" TO "anon", "authenticated", "postgres", "service_role";

-- Cron schedules are environment-specific and are managed outside this baseline.

CREATE INDEX match_alerts_user_idx ON public.match_alerts USING btree (user_id);

CREATE POLICY "Users can delete their alerts" ON "public"."match_alerts"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert alerts" ON "public"."match_alerts"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update their alerts" ON "public"."match_alerts"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view their alerts" ON "public"."match_alerts"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

ALTER TABLE "public"."user_preferences"
  ADD CONSTRAINT "user_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE POLICY "Users can insert their own row" ON "public"."user_preferences"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Users can read their own row" ON "public"."user_preferences"
  FOR SELECT
  TO PUBLIC
  USING ((user_id = auth.uid()));

CREATE POLICY "Users can update their own row" ON "public"."user_preferences"
  FOR UPDATE
  TO PUBLIC
  USING ((user_id = auth.uid()));
